#!/usr/bin/env bash
#This is a Bash script that gives us information about the "school" file.
file="school"

if [ -e "$file" ]; then

echo "school file exists"

if [ ! -s "$file" ]; then
echo "school file is not empty"
else
echo "school file is empty"
fi

if [ -f "$file" ]; then
fi
echo "school is a regular file"
else
echo "school file does not exist"
fi
