#!/usr/bin/env bash
#This is a Bash script that gives us information about the "school" file.
file="school"

#checking if the file exist in the first place
if [ -e "$file" ]; then

echo "school file exists"

#checking if the file is empty or not empty
if [ ! -s "$file" ]; then
echo "school file is empty"
else
echo "school file is not empty"
fi

#checking if the file is a regular file.
if [ -f "$file" ]; then
fi
echo "school is a regular file"
else
echo "school file does not exist"
fi
